---
title: Crime in Chicago
author: Sinclair Target
output: pdf_document
---

```{python, echo=FALSE}
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
```

```{python}
df_2017 = pd.read_csv('data/crimes2017.csv')
df_2018 = pd.read_csv('data/crimes2018.csv')
```

# Problem 1
## Types of Crime
Across all of Chicago, the most common crime in both 2017 and 2018 was theft.
Other common crimes included battery and assault.

```{python}
crimes_2017 = df_2017.groupby('Primary Type') \
                     .size() \
                     .sort_values(ascending=False).iloc[:5]
crimes_2017

crimes_2018 = df_2018.groupby('Primary Type') \
                     .size() \
                     .sort_values(ascending=False).iloc[:5]
crimes_2018
```

These most common five crimes were the same across both years. Thefts were the
most common crime by quite a ways, as can be seen in the following graphs:

```{python, results = 'hide'}
# 2017
plt.barh(crimes_2017.index.to_numpy(), crimes_2017.values)
plt.title('Most Common Crimes (2017)')
plt.xlabel('Occurrences')
plt.tight_layout()
plt.show()
plt.close()

# 2018
plt.barh(crimes_2018.index.to_numpy(), crimes_2018.values)
plt.title('Most Common Crimes (2018)')
plt.xlabel('Occurrences')
plt.tight_layout()
plt.show()
plt.close()
```

## Crime Over Time
We can see from the graph below that there is a seasonal pattern to crime. Most
crimes, such as theft and battery, spike in the summer. But there are other
crimes such as "deceptive practice" that spike in the winter.

```{python, results = 'hide'}
crimes = ['THEFT', 'ASSAULT', 'BATTERY', 'CRIMINAL DAMAGE', 'DECEPTIVE PRACTICE']

crimes_2018 = df_2018[df_2018['Primary Type'].isin(crimes)]

crimes_2018['Datetime'] = pd.to_datetime(crimes_2018['Date'])
crimes_2018 = (crimes_2018.groupby(['Primary Type', crimes_2018['Datetime'].dt.month])
                          .size()
                          .to_frame('Count')
                          .reset_index())

for crime in crimes:
    these_crimes = crimes_2018[crimes_2018['Primary Type'] == crime]
    plt.plot(these_crimes.Datetime.values, these_crimes.Count.values)

plt.xticks(range(1, 13), ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul',
                          'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

plt.title('Most Common Crimes Over Year (2018)')
plt.xlabel('Months')
plt.ylabel('Occurrences')
plt.legend(crimes, prop={'size': 6})

plt.show()
plt.close()
```

## Crime Locations
The community areas with the most crime (the 25th, 8th, 32nd, 28th, and 29th)
are all either downtown or on the west side.

```{python}
crimes_2017 = df_2017.groupby('Community Area') \
                     .size() \
                     .sort_values(ascending=False).iloc[:5]
crimes_2017

crimes_2018 = df_2018.groupby('Community Area') \
                     .size() \
                     .sort_values(ascending=False).iloc[:5]
crimes_2018
```

# Problem 2
## Battery
The median "Battery" crime occurs in a census tract that has a relatively low
median household income. The census tract is typically 80% black, 5% Hispanic
or Latino, and has a median age of 33.

```{python}
df = pd.read_csv('data/crimes2018_augmented.csv')
df['black_perc'] = df['black_pop'] / df['total_pop']
df['hispanic_perc'] = df['hispanic_pop'] / df['total_pop']

battery = df[df['Primary Type'] == 'BATTERY'].copy()
battery[battery.household_inc >= 0].household_inc.median()
battery[battery.black_perc >= 0].black_perc.median()
battery[battery.hispanic_perc >= 0].hispanic_perc.median()
battery[battery.median_age >= 0].median_age.median()
```

## Homicide
The median "Homicide" crime occurs in a poorer census tract than the median
"Battery" crime. This census tract is also more black (92%) and less Hispanic
or Latino (4%). The median age is more or less the same.

```{python}
homicide = df[df['Primary Type'] == 'HOMICIDE']
homicide[homicide.household_inc >= 0].household_inc.median()
homicide[homicide.black_perc >= 0].black_perc.median()
homicide[homicide.hispanic_perc >= 0].hispanic_perc.median()
homicide[homicide.median_age >= 0].median_age.median()
```

## Change Over Time
```{python}
battery['Datetime'] = pd.to_datetime(battery['Date'])

battery_jan = battery[battery['Datetime'].dt.month == 1]
battery_dec = battery[battery['Datetime'].dt.month == 12]

battery_jan[battery_jan.household_inc >= 0].household_inc.median()
battery_jan[battery_jan.black_perc >= 0].black_perc.median()
battery_jan[battery_jan.hispanic_perc >= 0].hispanic_perc.median()
battery_jan[battery_jan.median_age >= 0].median_age.median()

battery_dec[battery_dec.household_inc >= 0].household_inc.median()
battery_dec[battery_dec.black_perc >= 0].black_perc.median()
battery_dec[battery_dec.hispanic_perc >= 0].hispanic_perc.median()
battery_dec[battery_dec.median_age >= 0].median_age.median()
```

We can see from the above that there is not much change between the beginning
of 2018 and the end of 2018.

## Deceptive Practice and Sex Offense
```{python}
decept = df[df['Primary Type'] == 'DECEPTIVE PRACTICE']
sex = df[df['Primary Type'] == 'SEX OFFENSE']

decept[decept.household_inc >= 0].household_inc.median()
sex[sex.household_inc >= 0].household_inc.median()
```

One difference is that the median household income in census tracts with lots
of "Deceptive Practice" crimes was significantly higher than the median
household income in census tracts with lots of "Sex Offense" crimes.

# Problem 3
## Change in Crime
Crime seems to have changed very little in Chicago between 2017 and 2018. If
you look at the total number of crimes, for example, there has been no
significant increase or decrease.

```{python}
len(df_2017)
len(df_2018)
```

## The Aldermanic Candidate's Claims
These claims appear to be entirely wrong. Robbery seems to have fallen by about
10% (and not increased by 21%). Battery seems to have risen by 7% but not by
136%. Burglary has fallen slightly and not risen. The same goes for motor
vehicle theft.

```{python}
# Whether date is between 6/29 and 7/26 (inclusive)
def in_july(year, dt):
    start = pd.Timestamp(year, 6, 29)
    end = pd.Timestamp(year, 7, 26)
    return dt >= start and dt <= end

df_2017['Datetime'] = pd.to_datetime(df_2017['Date'])
df_2018['Datetime'] = pd.to_datetime(df_2018['Date'])

july_2017 = df_2017[df_2017['Datetime'].apply(lambda dt: in_july(2017, dt))]
july_2018 = df_2018[df_2018['Datetime'].apply(lambda dt: in_july(2018, dt))]

robbery_2017 = july_2017[july_2017['Primary Type'] == 'ROBBERY']
robbery_2018 = july_2018[july_2018['Primary Type'] == 'ROBBERY']
len(robbery_2018) / len(robbery_2017)

battery_2017 = july_2017[july_2017['Primary Type'] == 'BATTERY']
battery_2018 = july_2018[july_2018['Primary Type'] == 'BATTERY']
len(battery_2018) / len(battery_2017)

burglary_2017 = july_2017[july_2017['Primary Type'] == 'BURGLARY']
burglary_2018 = july_2018[july_2018['Primary Type'] == 'BURGLARY']
len(burglary_2018) / len(burglary_2017)

motor_2017 = july_2017[july_2017['Primary Type'] == 'MOTOR VEHICLE THEFT']
motor_2018 = july_2018[july_2018['Primary Type'] == 'MOTOR VEHICLE THEFT']
len(motor_2018) / len(motor_2017)
```

The claims are incorrect, so I do not agree with the conclusion. Overall, crime
in Chicago has not changed significantly. It might be possible to pick a few
select crimes to make it look as if crime is rising, but this is not the case.

## Advice for The New Mayor
1. Theft seems to be a big problem in Chicago. It is the largest single
   category of crimes. Since it is the largest crime category, reducing theft
   will significantly reduce overall crime.
2. Crime in Chicago is partly a seasonal phenomenon. Certain crimes,
   particularly theft and battery, seem to occur most often in the summer.
3. Homicides appear to be especially common in neighborhoods that at poorer and
   more black than the average neighborhood. This suggests that any kind of
   intervention to reduce homicides needs to consider how race plays a role.
4. Crime does not seem to be growing. The total number of crimes in 2018 was
   not significantly different from the total number of crimes in 2017. But
   this also means that efforts to reduce crimes have not been especially
   successful.
5. In Chicago, which is a highly segregated city, different neighborhoods tend
   to have different kinds of crimes. "Deceptive practice" crimes, for example,
   tend to be committed in relatively well-off neighborhoods.

## Caveats
A big, big caveat is that this dataset presumably only involves crimes that
have been observed or thwarted by police. So many crimes may still be taking
place that are not included in this dataset. What is doubly important to note
here is that some neighborhoods are probably more heavily policed than others,
so while we might have observed more "Sex Offense" crimes in lower income
neighborhoods in this dataset, the reality may just be that in higher income
neighborhoods "Sex Offense" crimes go unobserved.

Another potential problem is that it is not clear from the data alone how
crimes are categorized. Does a crime that involves robbery _and_ the theft of a
car count as one crime or two? If it counts as one, then should it be
categorized as "Motor Vehicle Theft" or "Robbery"? If it counts as two, then
wouldn't that make Chicago seems like a scarier place to live than it actually
is?

We should also always be worried about the quality of the data itself, because
the analysis can be no more accurate than the data provided. Police officers
may not have the time or inclination to record crime data accurately.
